version: '3.1'

services:
  mongo:
    container_name: ml-mongodb
    image: mongo:6.0.3
    restart: ${DOCKER_RESTART}
    ports:
      - "${MONGO_PORT}:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - .${MONGO_BACKUP_PATH}:${MONGO_BACKUP_PATH}
      - ./init-mongo.js:/docker-entrypoint-inititdb.d/init-mongo.js:ro
    # command:
    #   mongodump --host mongo_db --out /backup/${MONGO_BACKUP_PATH} --gzip --archive=/backup/${MONGO_BACKUP_PATH}/backup.gz